<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="34" passed="11" failed="23" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-20T15:23:50 IST" name="Suite" finished-at="2024-03-20T15:24:39 IST" duration-ms="49104">
    <groups>
      <group name="sanity">
        <method signature="Money_Control_L1_TestCases.verifyNavigateToHomePage()[pri:1, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="verifyNavigateToHomePage" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.click_Shop_Menu()[pri:2, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="click_Shop_Menu" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.navigate_to_Shop_page()[pri:3, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="navigate_to_Shop_page" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.click_on_cart()[pri:4, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="click_on_cart" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.navigateTobasketpage()[pri:5, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="navigateTobasketpage" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Home_menu()[pri:6, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Home_menu" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Click_on_Home()[pri:7, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Click_on_Home" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.navigateToHomePage()[pri:8, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="navigateToHomePage" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.new_arrival_is_present()[pri:9, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="new_arrival_is_present" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.seleniumu_Ruby_is_present()[pri:10, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="seleniumu_Ruby_is_present" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.one_product_isClickable()[pri:11, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="one_product_isClickable" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.navigates_to_Selenium_Ruby()[pri:12, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="navigates_to_Selenium_Ruby" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.add_to_basket()[pri:13, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="add_to_basket" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Click_on_add_to_basket()[pri:14, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Click_on_add_to_basket" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.verify_message()[pri:15, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="verify_message" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.GoToCart()[pri:16, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="GoToCart" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.CheckItem()[pri:17, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="CheckItem" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Apply_Coupon()[pri:18, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Apply_Coupon" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Price_Defined()[pri:19, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Price_Defined" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Price_Defined_in_correct_Format()[pri:20, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Price_Defined_in_correct_Format" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Quantity_Defined()[pri:21, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Quantity_Defined" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.quantity_Defined_in_correct_Format()[pri:22, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="quantity_Defined_in_correct_Format" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Total_Defined()[pri:23, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Total_Defined" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Total_Defined_in_Correct_Format()[pri:24, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Total_Defined_in_Correct_Format" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Tax_Defined()[pri:25, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Tax_Defined" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Tax_Defined_in_correct_Format()[pri:26, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Tax_Defined_in_correct_Format" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.remove_option_is_present()[pri:27, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="remove_option_is_present" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.remove()[pri:28, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="remove" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.ValidateAnRemoveMessage()[pri:29, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="ValidateAnRemoveMessage" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.updateQuantity()[pri:30, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="updateQuantity" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Update_Basket()[pri:31, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Update_Basket" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Proceed_to_checkout()[pri:32, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Proceed_to_checkout" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.Click_Proceed_to_checkout()[pri:33, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="Click_Proceed_to_checkout" class="testcases.Money_Control_L1_TestCases"/>
        <method signature="Money_Control_L1_TestCases.navigate_to_Billing_Details_page()[pri:34, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" name="navigate_to_Billing_Details_page" class="testcases.Money_Control_L1_TestCases"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2024-03-20T15:23:50 IST" name="Test" finished-at="2024-03-20T15:24:39 IST" duration-ms="49104">
      <class name="testcases.Money_Control_L1_TestCases">
        <test-method is-config="true" signature="initBrowser(java.lang.String,java.lang.String)[pri:0, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:23:50 IST" name="initBrowser" finished-at="2024-03-20T15:24:03 IST" duration-ms="13189" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dev]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initBrowser -->
        <test-method signature="verifyNavigateToHomePage()[pri:1, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:03 IST" name="verifyNavigateToHomePage" description="Verify navigate to the home page" finished-at="2024-03-20T15:24:03 IST" duration-ms="37" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Money_Control_L1_TestCases.verifyNavigateToHomePage(Money_Control_L1_TestCases.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNavigateToHomePage -->
        <test-method signature="click_Shop_Menu()[pri:2, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:03 IST" name="click_Shop_Menu" description=" Click on “Shop” Menu Option" finished-at="2024-03-20T15:24:07 IST" duration-ms="3792" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- click_Shop_Menu -->
        <test-method signature="navigate_to_Shop_page()[pri:3, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:07 IST" name="navigate_to_Shop_page" description="Check if the control is successfully navigated to “Shop” page." finished-at="2024-03-20T15:24:07 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Money_Control_L1_TestCases.navigate_to_Shop_page(Money_Control_L1_TestCases.java:100)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_to_Shop_page -->
        <test-method signature="click_on_cart()[pri:4, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:07 IST" name="click_on_cart" description="Go to cart(Click Cart icon)" finished-at="2024-03-20T15:24:10 IST" duration-ms="3240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- click_on_cart -->
        <test-method signature="navigateTobasketpage()[pri:5, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:10 IST" name="navigateTobasketpage" description="Check if it is navigated to basket page" finished-at="2024-03-20T15:24:10 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Money_Control_L1_TestCases.navigateTobasketpage(Money_Control_L1_TestCases.java:137)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateTobasketpage -->
        <test-method signature="Home_menu()[pri:6, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:10 IST" name="Home_menu" description="Check if “Home” Menu Option is available on navigated page." finished-at="2024-03-20T15:24:10 IST" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Home_menu(Money_Control_L1_TestCases.java:151)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Home_menu -->
        <test-method signature="Click_on_Home()[pri:7, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:10 IST" name="Click_on_Home" description="Check if “Home” Menu Option is available on navigated page." finished-at="2024-03-20T15:24:13 IST" duration-ms="3136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Click_on_Home -->
        <test-method signature="navigateToHomePage()[pri:8, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:13 IST" name="navigateToHomePage" description="Check if the control is successfully navigated to “Home” page." finished-at="2024-03-20T15:24:13 IST" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Money_Control_L1_TestCases.navigateToHomePage(Money_Control_L1_TestCases.java:191)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToHomePage -->
        <test-method signature="new_arrival_is_present()[pri:9, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:13 IST" name="new_arrival_is_present" description="Check if “Home” page has a section of new arrivals." finished-at="2024-03-20T15:24:16 IST" duration-ms="3159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- new_arrival_is_present -->
        <test-method signature="seleniumu_Ruby_is_present()[pri:10, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:16 IST" name="seleniumu_Ruby_is_present" description="Check of “Arrivals” section has selenium ruby is present" finished-at="2024-03-20T15:24:16 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.seleniumu_Ruby_is_present(Money_Control_L1_TestCases.java:222)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seleniumu_Ruby_is_present -->
        <test-method signature="one_product_isClickable()[pri:11, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:16 IST" name="one_product_isClickable" description="check one product is clickable" finished-at="2024-03-20T15:24:19 IST" duration-ms="2937" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- one_product_isClickable -->
        <test-method signature="navigates_to_Selenium_Ruby()[pri:12, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:19 IST" name="navigates_to_Selenium_Ruby" description="Check if the control is successfully navigated to Product Details page." finished-at="2024-03-20T15:24:19 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Money_Control_L1_TestCases.navigates_to_Selenium_Ruby(Money_Control_L1_TestCases.java:263)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigates_to_Selenium_Ruby -->
        <test-method signature="add_to_basket()[pri:13, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:19 IST" name="add_to_basket" description="Check if product details page has an option “ADD TO BASKET”." finished-at="2024-03-20T15:24:23 IST" duration-ms="3157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add_to_basket -->
        <test-method signature="Click_on_add_to_basket()[pri:14, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:23 IST" name="Click_on_add_to_basket" description="Click on “ADD TO BASKET” option." finished-at="2024-03-20T15:24:26 IST" duration-ms="3176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Click_on_add_to_basket -->
        <test-method signature="verify_message()[pri:15, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:26 IST" name="verify_message" description="Check if product added message is shown when product is added to basket. Check for message" finished-at="2024-03-20T15:24:26 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Money_Control_L1_TestCases.verify_message(Money_Control_L1_TestCases.java:317)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_message -->
        <test-method signature="GoToCart()[pri:16, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:26 IST" name="GoToCart" description="  Go to cart(Click Cart icon)" finished-at="2024-03-20T15:24:29 IST" duration-ms="3160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoToCart -->
        <test-method signature="CheckItem()[pri:17, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:29 IST" name="CheckItem" description="Check how many items are there in cart." finished-at="2024-03-20T15:24:29 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.CheckItem(Money_Control_L1_TestCases.java:350)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckItem -->
        <test-method signature="Apply_Coupon()[pri:18, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:29 IST" name="Apply_Coupon" description=" Check if we have “APPLY COUPON” button or not." finished-at="2024-03-20T15:24:32 IST" duration-ms="3067" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Apply_Coupon -->
        <test-method signature="Price_Defined()[pri:19, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:32 IST" name="Price_Defined" description="Check if we have price defined after product name." finished-at="2024-03-20T15:24:32 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Price_Defined(Money_Control_L1_TestCases.java:386)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Price_Defined -->
        <test-method signature="Price_Defined_in_correct_Format()[pri:20, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:32 IST" name="Price_Defined_in_correct_Format" description="Check if we have price defined in correct format or not" finished-at="2024-03-20T15:24:32 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Price_Defined_in_correct_Format(Money_Control_L1_TestCases.java:404)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Price_Defined_in_correct_Format -->
        <test-method signature="Quantity_Defined()[pri:21, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:32 IST" name="Quantity_Defined" description="Check if we have quantity defined after product price." finished-at="2024-03-20T15:24:32 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Quantity_Defined(Money_Control_L1_TestCases.java:422)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quantity_Defined -->
        <test-method signature="quantity_Defined_in_correct_Format()[pri:22, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:32 IST" name="quantity_Defined_in_correct_Format" description="Check if we have quantity defined in correct format or not." finished-at="2024-03-20T15:24:32 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.quantity_Defined_in_correct_Format(Money_Control_L1_TestCases.java:439)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quantity_Defined_in_correct_Format -->
        <test-method signature="Total_Defined()[pri:23, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:32 IST" name="Total_Defined" description="Check if we have total defined after quantity." finished-at="2024-03-20T15:24:32 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Total_Defined(Money_Control_L1_TestCases.java:456)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Total_Defined -->
        <test-method signature="Total_Defined_in_Correct_Format()[pri:24, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:32 IST" name="Total_Defined_in_Correct_Format" description="Check if we have total defined in correct format or not." finished-at="2024-03-20T15:24:32 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Total_Defined_in_Correct_Format(Money_Control_L1_TestCases.java:473)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Total_Defined_in_Correct_Format -->
        <test-method signature="Tax_Defined()[pri:25, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:32 IST" name="Tax_Defined" description="Check if we have Tax defined after product name." finished-at="2024-03-20T15:24:32 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Tax_Defined(Money_Control_L1_TestCases.java:489)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Tax_Defined -->
        <test-method signature="Tax_Defined_in_correct_Format()[pri:26, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:32 IST" name="Tax_Defined_in_correct_Format" description="Check if we have Tax defined in correct format or not." finished-at="2024-03-20T15:24:32 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Tax_Defined_in_correct_Format(Money_Control_L1_TestCases.java:506)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Tax_Defined_in_correct_Format -->
        <test-method signature="remove_option_is_present()[pri:27, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:32 IST" name="remove_option_is_present" description="Validate if we have an option to remove an added product or not." finished-at="2024-03-20T15:24:35 IST" duration-ms="3205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- remove_option_is_present -->
        <test-method signature="remove()[pri:28, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:35 IST" name="remove" description="Remove a product." finished-at="2024-03-20T15:24:38 IST" duration-ms="3171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- remove -->
        <test-method signature="ValidateAnRemoveMessage()[pri:29, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:38 IST" name="ValidateAnRemoveMessage" description="Validate if we get a message after removing an item with its name or not." finished-at="2024-03-20T15:24:38 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Money_Control_L1_TestCases.ValidateAnRemoveMessage(Money_Control_L1_TestCases.java:563)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateAnRemoveMessage -->
        <test-method signature="updateQuantity()[pri:30, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:38 IST" name="updateQuantity" description="Update the quantity of one of the product. Increase quantity by 1" finished-at="2024-03-20T15:24:38 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.updateQuantity(Money_Control_L1_TestCases.java:578)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateQuantity -->
        <test-method signature="Update_Basket()[pri:31, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:38 IST" name="Update_Basket" description="Validate if we have active Update Basket button active on updating quantity or not." finished-at="2024-03-20T15:24:38 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Update_Basket(Money_Control_L1_TestCases.java:595)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Update_Basket -->
        <test-method signature="Proceed_to_checkout()[pri:32, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:38 IST" name="Proceed_to_checkout" description="Validate if we have a “Proceed to checkout” button or not." finished-at="2024-03-20T15:24:38 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Proceed_to_checkout(Money_Control_L1_TestCases.java:613)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Proceed_to_checkout -->
        <test-method signature="Click_Proceed_to_checkout()[pri:33, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:38 IST" name="Click_Proceed_to_checkout" description="Click on “Proceed to checkout” button." finished-at="2024-03-20T15:24:38 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected object to not be null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.assertNotNull(Assert.java:1484)
at org.testng.Assert.assertNotNull(Assert.java:1468)
at testcases.Money_Control_L1_TestCases.Click_Proceed_to_checkout(Money_Control_L1_TestCases.java:631)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Click_Proceed_to_checkout -->
        <test-method signature="navigate_to_Billing_Details_page()[pri:34, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:38 IST" name="navigate_to_Billing_Details_page" description="On clicking it, validate do we navigate to Billing Details page having “Billing Details” as heading or not" finished-at="2024-03-20T15:24:38 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Money_Control_L1_TestCases.navigate_to_Billing_Details_page(Money_Control_L1_TestCases.java:653)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_to_Billing_Details_page -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.Money_Control_L1_TestCases@2d6c53fc]" started-at="2024-03-20T15:24:38 IST" name="tearDown" finished-at="2024-03-20T15:24:39 IST" duration-ms="320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.Money_Control_L1_TestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
